// <auto-generated />
namespace TaobaoMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class haha1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(haha1));
        
        string IMigrationMetadata.Id
        {
            get { return "201501030304547_haha1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
