// <auto-generated />
namespace TaobaoMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class haha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(haha));
        
        string IMigrationMetadata.Id
        {
            get { return "201501030233458_haha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
